#!/bin/bash
#SBATCH -A TG-CCR140008
#SBATCH -J geneticTSP
#SBATCH -o cudaGA.out 
#SBATCH -n 1
#SBATCH -p gpudev
#SBATCH -t 02:00:00

nvcc -arch=compute_35 -code=sm_35 geneticTSP.cu -o tsp.out
ibrun ./tsp.out -o
# TO DEBUG YO CODE:
#nvcc -G -g -arch=compute_35 -code=sm_35 geneticTSP.cu -o tsp.out
#cuda-memcheck ./tsp.out -o
