#!/bin/bash
#SBATCH -J gaTSP
#SBATCH -N 1 -n 1
#SBATCH -o cudaGA.out 
#SBATCH -p gpu
#SBATCH -t 00:30:00
module load cuda
nvcc -arch=compute_35 -code=sm_35 geneticTSP.cu -o tsp.out
ibrun ./tsp.out -o
# TO DEBUG YO CODE:
#nvcc -G -g -arch=compute_35 -code=sm_35 geneticTSP.cu -o tsp.out
#cuda-memcheck ./tsp.out -o
